import { LEVELS_PER_GAME } from '../lib/catalog.js';

/**
 * StartScreen
 * Full-screen window shown before a game begins. The player picks the game
 * mode — real 360° photos or AI-generated scenes — and starts the 5 levels.
 *
 * Props:
 *   - onStart: (mode: 'real' | 'ai') => void
 */
export default function StartScreen({ onStart }) {
  return (
    <div className="auth-overlay">
      <div className="auth-card start-card">
        <h1>🌍 EraGuessr</h1>
        <p className="auth-sub">
          {LEVELS_PER_GAME} levels — guess the place and the year. Pick a mode:
        </p>

        <button
          className="mode-option"
          onClick={() => onStart('real')}
        >
          <span className="mode-emoji" aria-hidden="true">📷</span>
          <span className="mode-text">
            <span className="mode-title">Real photos</span>
            <span className="mode-desc">Explore true 360° panoramas</span>
          </span>
        </button>

        <button
          className="mode-option"
          onClick={() => onStart('ai')}
        >
          <span className="mode-emoji" aria-hidden="true">✨</span>
          <span className="mode-text">
            <span className="mode-title">AI-generated scenes</span>
            <span className="mode-desc">
              Every level is freshly generated by AI
            </span>
          </span>
        </button>
      </div>
    </div>
  );
}
